### ISSUE TITLE
Add pagination to show posts

### ISSUE THREAD

**Issue by Nxtra** [z3by/vuepress-theme-modern-blog#11]
Is there a way to enable pagination for this template?

Having 20 blogposts will make a list 20 posts appear on the first page.
It would be nice to have be able to show  for example 5 per page.

**Comment by stuta** [comment]
Documentation does not tell you where (what file) file should I put these options.
Where is this modifyBlogPluginOptions() defined?

I tried this in .vuepress/config.js, but modifyBlogPluginOptions is undefined. Setting directories -tag inside themeConfig does not work either.

```js
module.exports = themeConfig => {
	const { modifyBlogPluginOptions } = themeConfig
	console.log('modifyBlogPluginOptions', modifyBlogPluginOptions)
```

**Comment by Nxtra** [comment]
Great, thanks! My bet, it's even in the README.
