### ISSUE TITLE
"plugins" folder is missing in packaged version

### ISSUE THREAD

**Issue by alexandernst** [z3by/vuepress-theme-modern-blog#33]
@z3by I just checked the v1.10.0 release, and the "plugins" folder is missing, causing an error. I'm not sure if that is because of some packaging scripts that you're using that is ignoring that folder or if I should fix it something form the code.

**Comment by z3by** [comment]
Thank you for reporting this issue! there was a problem while publishing, it should be 2.10 I will deprecate this version and republish it with another version.

**Comment by z3by** [comment]
Sorry for the inconvenience, I deprecated the wrong version name, amended the commit, and re-published under version 2.10.0

**Comment by z3by** [comment]
I included the plugins folder in the package as well.
